### ISSUE TITLE
0.1.1 introduced a breaking semver change

### ISSUE THREAD

**Issue by hackerbirds** [RustCrypto/KEMs#31]
Hi, it seems that going from `0.1.0` to `0.1.1` broke the public API, with the change at #15.

I understand the library is still a work in progress, but I wanted to know if this library wasn't supposed to guarantee semantic versioning yet, or was that a mistake because of the Kyberslash issue being pushed too quickly? 

If semver isn't guaranteed yet I think it would be useful to mention it in the README or docs.

**Comment by tarcieri** [comment]
It was a mistake. The version probably should've been bumped to v0.2.

**Comment by tarcieri** [comment]
Going to close this with "we'll do better in the future".

The v0.1.0 release has been yanked, so you can consider v0.1.1 the API to target.

**Comment by hackerbirds** [comment]
Alright, thanks for your quick response
