### ISSUE TITLE
Can `ml-kem` re-export `kem::Decapsulate` and other third party traits?

### ISSUE THREAD

**Issue by faern** [RustCrypto/KEMs#36]
Hi. I'm trying to use `ml-kem`. But to do the decapsulation operation, I must have the `kem::Decapsulate` trait in scope. And this comes from another crate. Currently as far as I can tell, the only way to solve this is for *me* to depend directly on `kem`. This is not very ergonomic and a bit verbose. This likely means I need to upgrade two crates every time I want to upgrade `ml-kem`.

IMHO it's usually best to publicly re-export most third party stuff that a crate exposes in its public API. Sorry if this has been discussed and decided against earlier, I could not find any related issue.

**Comment by tarcieri** [comment]
Sure, we can add a re-export for `kem`. It's pretty standard practice for the @RustCrypto crates

**Comment by faern** [comment]
Awesome! The same holds for `hybrid_array::Array`. It's an important part of the public API of `ml-kem`, but I have to depend on `hybrid-array` myself to get access to the type.
