### ISSUE TITLE
ml-kem: make `encapsulation_key()` public

### ISSUE THREAD

**Issue by commial** [RustCrypto/KEMs#39]
Hello,

For easier integration with others crates and simplify some `ml-kem` use cases, it would be nice to have a way to obtain the encapsulation key from the decapsulation one.
It seems that this is already possible and done inside the crate, but the related function is not published publicly:

https://github.com/RustCrypto/KEMs/blob/a8315adc8e21bec8206cd27720c993d9b0728606/ml-kem/src/kem.rs#L109

Would it be possible to make it widely available, or am I missing an already existing method to obtain the encapsulating key from the decapsulation key?

**Comment by tarcieri** [comment]
Barring some resolution on what the traits should look like, I think we can start by making `encapsulation_key` public

**Comment by incertia** [comment]
I don't see anything wrong with making it public, although I'm not the original owner of this code.

**Comment by tarcieri** [comment]
If someone wants to open a PR we can move forward on making it public
