### ISSUE TITLE
Support "zeroize" for ML-KEM decapsulation key

### ISSUE THREAD

**Issue by commial** [RustCrypto/KEMs#40]
Hello,

In the `dhkem` crate, the `Zeroize` trait is supported through a feature named `zeroize`:
https://github.com/RustCrypto/KEMs/blob/a8315adc8e21bec8206cd27720c993d9b0728606/dhkem/src/lib.rs#L71

Would it be possible to have the same support for `zeroize` in `mlkem`, at least for the decapsulation key?
It might be already planned.

**Comment by tarcieri** [comment]
Yes, it'd be a good idea

**Comment by tarcieri** [comment]
Fixed in #51
