### ISSUE TITLE
ml-kem: update to FIPS 203 final

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/KEMs#46]
It's out: https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.203.pdf

cc @bifurcation 

> ### C.2 Changes From FIPS 203 Initial Public Draft
>The differences between CRYSTALS-KYBER and ML-KEM as described in Appendix C were included
> in the initial public draft (ipd) of FIPS 203, which was posted on August 24, 2023. Based on
> comments submitted on the draft ML-KEM, domain separation was added to K-PKE.KeyGen to
> prevent the misuse of keys generated to target one security level from being used for a different
> security level when saving a key as a seed.
> Additionally, FIPS 203 ipd had inadvertently swapped the indices of matrix 𝐀̂in K-PKE.KeyGen and
> K-PKE.Encrypt. This was changed back in the final version of ML-KEM to match CRYSTALS-KYBER.

**Comment by tarcieri** [comment]
Looks like there was a mistake in the "final" spec:

https://groups.google.com/a/list.nist.gov/d/msgid/pqc-forum/CO6PR09MB759124EB4EF0B2F7C961BC47F0862%40CO6PR09MB7591.namprd09.prod.outlook.com

> You are correct on the ML-DSA KeyGen issue. We’ve put in a fix that should go out either later today or tomorrow. Another user on the forum pointed out a similar issue for ML-KEM KeyGen under K-PKE.KeyGen. In both cases, the matrix dimensions were added to the seed, then hashed to form the key material. This is different than the draft FIPS, but covered in Appendix C.2 in FIPS 203, and Appendix D.3 in FIPS 204.

**Comment by bifurcation** [comment]
@tarcieri This seems like it probably merits a version bump and new crate version?

**Comment by tarcieri** [comment]
Yep, just wanted to close out those other issues. We're ready to cut a release I'd say.

**Comment by bifurcation** [comment]
If you want to hold for a second, I might write a quick fix for #40

**Comment by tarcieri** [comment]
Cool, I opened #50 but I can wait to get that in
