### ISSUE TITLE
Is there any way to get the length of the ciphertext?

### ISSUE THREAD

**Issue by faern** [RustCrypto/KEMs#68]
I can't find any way to get the length of ciphertexts for `ml_kem`. It's hard to figure out because of many levels of generics. But probably inaccessible mostly because `PkeParams` is a private trait.

My use case is that I get ciphertext from a remote party, and I need to pass it into my `DecapsulationKey<MlKem1024Params>::decapsulate` method. But I can't find any way to "know" the length of the expected array. I can use `Array::try_from` and rely on type inference to figure out the generic parameters to `Array` to delegate the length checking. But I have no way to get the length *out* of the library if I want to include the expected ciphertext length in the error message etc. The best I have found is to do the equivalent of:
```rust
let ciphertext_array = Array::try_from(ciphertext_slice).map_err(|_| {
    panic!("Unexpected length of ciphertext. But I can't print you the expected size, because no way of getting it :(");
})?;

decapsulation_key.decapsulate(&ciphertext_array).unwrap();
```

**Comment by tarcieri** [comment]
The size is specified as [`KemCore::CiphertextSize`](https://docs.rs/ml-kem/latest/ml_kem/trait.KemCore.html#associatedtype.CiphertextSize).

The [`Ciphertext`](https://docs.rs/ml-kem/latest/ml_kem/type.Ciphertext.html) type alias will give you an appropriately sized `Array` for the given algorithm.

**Comment by faern** [comment]
@tarcieri So the only way I find to get the length of an array type is the following:

```rust
use ml_kem::{KemCore, MlKem1024};
// Must be imported to get access to the USIZE
use ml_kem::array::typenum::marker_traits::Unsigned;

let len = <MlKem1024 as KemCore>::CiphertextSize::USIZE;
```

Is there a better way? This is very convoluted :see_no_evil: It took me quite a long time juggling types to arrive to this.

The problem is that there are so many levels of types (with generics) that has to be traversed in order to reach such a simple thing. To get the expected length of any type of key/ciphertext in this library you have to go via: Kem type (eg. `MlKem1024`) -> `ml_kem::ArraySize` -> `hybrid_array::ArraySize` -> `typenum::Unsigned`. It involves traits from two crates outside of `ml_kem` itself. Everything you need is luckily re-exported :pray: But you have to go two levels of crate re-exports to reach the needed `Unsigned` trait.

**Comment by faern** [comment]
One direct improvement could be that `ArraySize` directly has a `LEN` constant on it. The value is automatically taken from the `Unsigned` impl below, but it's exposed in a higher layer. This removes the need to know anything about `typenum` to get the length.

**Comment by tarcieri** [comment]
Yes, that’s how to do it.

Eventually this will all go away and be replaced by const generics, but unfortunately we’re currently limited by the inability to use an associated constant as an array size.
