### ISSUE TITLE
Inner implementations for encapsulation and decapsulation keys prevent adding new `From` implementations.

### ISSUE THREAD

**Issue by tbrezot** [RustCrypto/KEMs#77]
# Problem

- Compilation does not terminate with toolchain v1.82.
- Compilation fails with nightly toolchain v1.84 with error:
```
error[E0119]: conflicting implementations of trait `From<DK>` for type `DK`
  --> src/main.rs:10:1
   |
10 | impl From<DK512> for DK {
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;

For more information about this error, try `rustc --explain E0119`.
```

# Steps to reproduce the issue

Compile the following `main.rs`:

```rust
use ml_kem::{self, KemCore};

// Alias the type since it is ugly to read.
type DK512 = <ml_kem::MlKem512 as KemCore>::DecapsulationKey;

// Encapsulate it.
pub struct DK(DK512);

// Implement the conversion from the wrapped type to the wrapper one.
impl From<DK512> for DK {
    fn from(value: DK512) -> Self {
        Self(value)
    }
}

fn main() {
    println!("you will never print this line");
}
```

Same issue when using the encapsulation key instead.

**Comment by newpavlov** [comment]
It looks like a problem with the Rust toolchains and not with our code. Have you tried to search the Rust issue tracker?

**Comment by tbrezot** [comment]
Indeed, it really looks like [this issue](https://github.com/rust-lang/rust/issues/85576#issuecomment-2058244779). However my situation differs in that I seem to have run into an infinite loop.

I will report my issue there, thanks for the redirection!
